### ISSUE TITLE
Persistence layer for WsFederation configuration data

### ISSUE THREAD

**Issue by rklachko** [IdentityServer/IdentityServer3.WsFederation#1]
Persistence layer for relying parties configuration that uses EntityFramework.

Note: I wasn't sure if this issue belong here or in Thinktecture.IdentityServer.v3.EntityFramework.

**Comment by scottbrady91** [comment]
Does this still need doing? If so I'm happy to publish one. Would you prefer a separate package or a PR somewhere?

**Comment by leastprivilege** [comment]
@brockallen would it make sense to put that into the EF repo?

**Comment by brockallen** [comment]
@leastprivilege no, as it adds a dependency to the ws-fed assembly/nuget.
