### ISSUE TITLE
WsFederationController does not honor IdentityServerOptions.PublicOrigin when calculating ReturnURL

### ISSUE THREAD

**Issue by santiagovm** [IdentityServer/IdentityServer3.WsFederation#27]
When Identity Server is deployed behind a load balancer with SSL termination at the load balancer, one can use the IdentityServerOptions.PublicOrigin to control the URLs that are generated by Identity Server and make sure they look like the load balancer's endpoint.

Say the load balancer endpoint is https://my-public-id-srv and the nodes listen on http://node1:8080 and http://node2:8080. Notice that load balancer requires SSL while the nodes do not.

For this setup one sets a couple of properties in the IdentityServerOptions object:

IdentityServerOptions.PublicOrigin = "https://my-public-id-srv"
IdentityServerOptions.RequireSsl = False

There is an issue with the WSFederationController. In this setup, the Controller is generating a return URL with http instead of https.

Rather than getting the RequestUri like this:

string requestUri = Request.RequestUri.AbsoluteUri

Something like this should be used to honor the PublicOrigin property:

string identityServerHost = Request.GetOwinContext().Environment.GetIdentityServerHost();
string pathAndQuery = Request.RequestUri.PathAndQuery;
string requestUri = identityServerHost + pathAndQuery;

Regards,
-Santiago

PS: Yesterday opened a similar issue in the Google+ provider. (https://github.com/owin-middleware/OwinOAuthProviders/issues/57)

**Comment by leastprivilege** [comment]
Thanks! You are right.

**Comment by leastprivilege** [comment]
Feel free to send a PR

**Comment by santiagovm** [comment]
Made some changes and managed to have a local version working as expected. Will submit a pull request in a few days when I get some time.

-S

**Comment by leastprivilege** [comment]
got some time already?

**Comment by santiagovm** [comment]
Hi Dominick,

 

Things are less hectic. I will submit the fix tomorrow.

 

-S

**Comment by leastprivilege** [comment]
merged on dev
