### ISSUE TITLE
[Question] What is the best approach for handling redirects on post actions (form post)

### ISSUE THREAD

**Issue by rayph** [IdentityServer/IdentityServer3.WsFederation#37]
I have cases where the POST of a form can cause an authorize redirect back to the Id Server to re-validate the token or ask the user to log in again, which is generally good except that the return url is not applicable for a GET request

-- Is there a good approach / pattern that can be applied to handle these cases?

Context: 

RP apps which have been migrated from their own Forms Auth to now use IdSrv + WsFed. 

It is reasonable to assume that folks may spend quite some time on a page before actually submitting the form.

This app is Asp.Net MVC though answers can be less specific

I also realise this is not strictly a WsFed problem but rather a question on how best to put it into practice with existing applications.

**Comment by rayph** [comment]
*Maybe* this is a silly question, it seems to me that all RP form POST urls that require authorization need to support a GET action that can be called that allows the end user to resume the flow... If someone else is discovering this I'd love to hear their thoughts about it.

**Comment by brockallen** [comment]
This is a really hard problem to solve in general web development. The user fills in a bunch of fields, and your server decides that it wants to redirect the user somewhere else -- how do you not lose the data? You'd have to capture it somehow in the server, redirect the user, and then when they come back re-submit this data (or just process it as if they had submitted). Also, what happens with multiple tabs? It's not trivial, so most people just say "screw it" and just accept that sometimes the user has to reenter the data.

**Comment by rayph** [comment]
You are right, it seems each case needs to be handled individually so there is no silver bullet.
