### ISSUE TITLE
Integrate with Azure ACS

### ISSUE THREAD

**Issue by jeremy001181** [IdentityServer/IdentityServer3.WsFederation#40]
Hi

I setup my idsrv with wsfed plugin, and everything works if I configure my relying parties to point at idsrv wsfed endpoint directly, but it fails if I have a azure ACS sit in the middle, basically i want following infrastructure:

RP ===> ACS ===> idsrv3

what happen is the idsrv receives request from ACS with ws-fed protocol and generates wsfed request message successfully, then it detects the end user hasn't been authenticated, which then it generates a signin message cookie so that the end user can sign in from login page.

The problem is that the signin message cookie doesn't get render out to browser, I debug through the whole pipeline, and found that it is because the signin cookie added to the OwinContext gets removed later on during the pipeline. 

Further more, I also notice that the reason why though ACS doesn't work is because the wsfed request sent from ACS has encrypted wctx parameter as belowed, and if I change it to a dummy value , the signinmessage cookie wont be removed.

because lack of signin message cookie, i got an error on login page:

"There is an error determining which application you are signing into. Return to the application and try again."

Does anyone know why please?

Ming
 
![acs](https://cloud.githubusercontent.com/assets/2342277/7770824/1e6e903a-008a-11e5-9c02-f440805a0999.png)

**Comment by brockallen** [comment]
There is a well-known bug in ASP.NET with OWIN/Katana. This has been discussed before - search the archives. Also, check the codeplex issue tracker for Katana.

**Comment by jeremy001181** [comment]
Thank you for your reply

I searched on issue tracker on codeplex for katana, can't find a thing related to my issue, can you let me know on which site has it been discussed before? 

Thanks

**Comment by brockallen** [comment]
It has to do with ASP.NET and OWIN cookies overwriting one another.

**Comment by jeremy001181** [comment]
changed add coodies to IOwinContext consistently through whole project fixes it

**Comment by brockallen** [comment]
Excellent!
