### ISSUE TITLE
Custom login screen based on RelyingParty and User

### ISSUE THREAD

**Issue by Thor-Kristian-Valderhaug** [IdentityServer/IdentityServer3.WsFederation#42]
HI
I'm using Identity Server along with WsFederationPlugin to provide a Identity Server for three groups of users from two separate systems / dependent parties. Preferably I will show a separate login screen based on which rely party and user login request comes from, but if this is impossible, I will show a seperate login sceens based on the relying party. And so have a selection screen for the user to trust the party with two user groups.

Any help will be appreciated, thanks in advance!

**Comment by brockallen** [comment]
Right now we don't pass any params to the login part of IdSvr from Ws-Fed with any RP info. It's possible that we could.

@leastprivilege thoughts?

**Comment by Thor-Kristian-Valderhaug** [comment]
Hi,

I found a solution/workaround. By implementing a custom ViewService I was able to use the information provided in the SignInMessage to differentiate the system and user group initiating the login request

**Comment by deslee** [comment]
Hi @Thor-Kristian-Valderhaug ,

We're also trying to use ws-federation with relying parties and a CustomViewService to display different login pages per relying party. However, we don't have any useful information provided to the SignInMessage in IViewService's Login method. 

Did you have to configure anything to get SignInMessage's fields to be populated?

An example of my relying party:

    new RelyingParty
                {
                    Realm = ConfigurationManager.AppSettings.Get("CustomerPortalRealm"),
                    Name = ConfigurationManager.AppSettings.Get("CustomerPortalDisplayName"),
                    Enabled = true,
                    ReplyUrl = ConfigurationManager.AppSettings.Get("CustomerPortalReplyUrl"),
                    TokenType = "urn:ietf:params:oauth:token-type:jwt",
                    TokenLifeTime = 20,
                    ClaimMappings = ClaimMappings
                }

and this is how we configured ws federation:

    private void ConfigureWsFederation(IAppBuilder pluginApp, IdentityServerOptions options)
        {
            var factory = new WsFederationServiceFactory(options.Factory);

            // data sources for in-memory services
            factory.Register(new Registration<IEnumerable<RelyingParty>>(RelyingParties.Get()));
            factory.RelyingPartyService = new Registration<IRelyingPartyService>(typeof(InMemoryRelyingPartyService));

            var wsFedOptions = new WsFederationPluginOptions
            {
                IdentityServerOptions = options,
                Factory = factory,
                EnableMetadataEndpoint = true
            };
            
            pluginApp.UseWsFederationPlugin(wsFedOptions);
        }

Thanks in advance for any help you can provide.

**Comment by leastprivilege** [comment]
As @brockallen said earlier - we don't populate the SignInMessage from WS-Fed. We simply never got to it. Feel free to start a PR.
