### ISSUE TITLE
ReturnUrl is mangled/corrupted by ToString call

### ISSUE THREAD

**Issue by Remfin** [IdentityServer/IdentityServer3.WsFederation#47]
The fix for #27 changed a line from .AbsoluteUri to .ToString(). The ToString() method for Uri does a multi-level unescape on the query string which essentially corrupts the Uri.

As an example, WIF redirects embed escaped values in a query string parameter to read on return, .ToString() unescapes recursively into plain text, and terminates the string when it sees a "bad" query string (extra =).

We haven't noticed any issues with changing it back to AbsoluteUri, and #27 still seems to be fixed.

**Comment by leastprivilege** [comment]
send a PR please.

**Comment by leastprivilege** [comment]
yes or no?

**Comment by Remfin** [comment]
Sorry, can't right now

**Comment by leastprivilege** [comment]
done and published.
