### ISSUE TITLE
SharePoint 2013 setup

### ISSUE THREAD

**Issue by ovidiubechesenoro** [IdentityServer/IdentityServer3.WsFederation#50]
Hello guys,

Starting with this post http://www.wictorwilen.se/using-sharepoint-2013-with-thinktecture-identityserver-2 I wanna implement the same setup but using IS3 and WSFederation. Is this possible ? Can I use IS3 with WS-Federation to generate SAML1.1 tokens ? 

If yes, how can I get the signinurl and Federation metadata xml ? 

I have IS3 running, now I need a bit of guidance to connect SharePoint 2013 with IS3.

Thank you,

Ovidiu

**Comment by leastprivilege** [comment]
Yes you can generate SAML 1.1 tokens.

I don't know how to connect SharePoint but this has been done before. There is also a WS-Fed sample client in the clients sample in our repo.

Would be great if you could post a walkthrough when you have it working.

**Comment by brockallen** [comment]
> Would be great if you could post a walkthrough when you have it working.

@ovidiubechesenoro were you able to do this?
