### ISSUE TITLE
Filter/alter claims before returned by SignInResponseGenerator

### ISSUE THREAD

**Issue by VictorBlomberg** [IdentityServer/IdentityServer3.WsFederation#51]
Hi!

We want to filter/alter claims sent to relying parties, depending on the user and relying party. Currently, we do it in a custom `SignInResponseGenerator` implementation (inheriting `SignInResponseGenerator`), in `CreateSubjectAsync(SignInValidationResult)`.

````C#
protected override async Task<ClaimsIdentity> CreateSubjectAsync(SignInValidationResult validationResult)
{
    var subject = await base.CreateSubjectAsync(validationResult);
    return new ClaimsIdentity(
        await TransformClaimsAsync(validationResult, subject),
        subject.AuthenticationType, 
        subject.NameClaimType,
        subject.RoleClaimType);
}

private async Task<IEnumerable<Claim>> TransformClaimsAsync(SignInValidationResult validationResult, ClaimsIdentity subject)
{
    [...]
}
````
Is there a better way? The obvious issue with this solution, is that the `CreateSubjectAsync(SignInValidationResult)` method is a private non-virtual method, and to be able to do the stuff above we have to keep a fork where the method signature is changed to *protected virtual* instead.

If this use case seems relevant to you, one option would of course be to change the signature of the method in this repo.

I'll happily create PRs, provide more detailed explanations and such if in any way needed. I'm also available in the gitter channel.

**Comment by leastprivilege** [comment]
Sounds useful. I just don't have the time right now to look into it.

It should probably "feel" like all the other extensibility points in idsrv - with support in the factory etc..

**Comment by VictorBlomberg** [comment]
Thank you for your reply! I'll try to come up with something that fits then, and make a PR of it, to ease the process a bit.

**Comment by VictorBlomberg** [comment]
Hi, as I'm sure you've been notified about, I've submitted a PR with #54.

**Comment by leastprivilege** [comment]
Hey, 

thanks! Will look into it ASAP. But I am very busy right now.

**Comment by VictorBlomberg** [comment]
Yeah, no hurry. :)

**Comment by scottbrady91** [comment]
@leastprivilege This has been resolved and can be closed now.
