### ISSUE TITLE
acr_values

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer3.WsFederation#52]
I'm not having acr_values carry through to my user service when using ws-fed.

Are these not enabled for the ws-fed plugin or do you only use standard ws-fed parameters?

FYI I'm after the Tenant acr_value in particular

**Comment by leastprivilege** [comment]
WS-Fed does not have an acr_value parameter. That's why it is not implemented.

**Comment by scottbrady91** [comment]
Sure, I understand ws-fed itself doesn't. Was working off of your comments in issue #19, that you may have implemented them.

Any recommendations for getting a Tenant value then? Obviously the full requesting url rocks up in the User Service and I can see any extra parameters there...

**Comment by leastprivilege** [comment]
Not sure I want to introduce proprietary parameters to wsfed.

**Comment by scottbrady91** [comment]
No worries, introducing proprietary parameters into your library wasn't the aim here.

I'm sure I'll figure something out :)
