### ISSUE TITLE
Default metadata missing <IDPSSODescriptor> and <SPSSODescriptor>

### ISSUE THREAD

**Issue by nzpcmad** [IdentityServer/IdentityServer3.WsFederation#53]
The default metadata does not have these two descriptors. 

There doesn't seem to be any way to "turn them on"?.

If you want to use e.g. ADFS as the IDP, when you import the default metadata, ADFS throws an error because the Descriptor elements are missing.

Is there any way to add these to the metadata?

**Comment by leastprivilege** [comment]
yes - via a PR ;)

**Comment by leastprivilege** [comment]
will you do that?

**Comment by nzpcmad** [comment]
I've been pondering on this a bit more.

The thing is that these descriptors are only for SAML which ws-fed obviously doesn't support.

Why does ADFS reject it?

So I took the ADFS metadata itself, removed both descriptors and it imported no problem.

So there must be something in the ADFS WS-Fed metadata that's missing in the idsrv metadata?

I'll keep looking.

**Comment by leastprivilege** [comment]
thanks!

— 
cheers
Dominick Baier


On 17 November 2015 at 21:26:45, nzpcmad (notifications@github.com) wrote:

I've been pondering on this a bit more.

The thing is that these descriptors are only for SAML which ws-fed obviously doesn't support.

Why does ADFS reject it?

So I took the ADFS metadata itself, removed both descriptors and it imported no problem.

So there must be something in the ADFS WS-Fed metadata that's missing in the idsrv metadata?

I'll keep looking.
