### ISSUE TITLE
WsFed logout endsession endpoint doesn't redirect to post_logout_redirect_uri

### ISSUE THREAD

**Issue by YuliaNaumenko** [IdentityServer/IdentityServer3.WsFederation#59]
We are able to successfully login to the client SPA application using our IdP server (IdentityServer3 1.6.3 + Microsoft.Owin.Security.WsFederation 3.0.1) with different providers.
But logout with **endsession** endpoint doesn't redirect to post_logout_redirect_uri for windows authentication flow. 
After logout the page is redirected to https://idphost/IdP/?wtrealm=urn%3aidp%3alocal&wa=wsignout1.0 instead of client address which was set in post_logout_redirect_uri.
Setting **wreply** didn't help, only added this param with value to ACS WS-Federation endpoint.

**Comment by leastprivilege** [comment]
what does "windows authentication flow" mean. On which idp does the sequence end? Maybe related to https://github.com/IdentityServer/IdentityServer3.WsFederation/issues/29

**Comment by YuliaNaumenko** [comment]
I meant that we are using WS-Federation running as an external provider to login using Windows Authentication. If users are part of the domain they can use the Windows button in the External Login section.
The sequence ends on WS-Federation provider single sign-out request.
And yes, it seems to be ralated to [#29.](https://github.com/IdentityServer/IdentityServer3.WsFederation/issues/29) But I cannot find the solution here.

**Comment by leastprivilege** [comment]
You can suppress the signout to the windows provider by handling the RedirectToIdentityProvider event in the ws-fed middleware. Call `Handled()` for signout requests.

**Comment by YuliaNaumenko** [comment]
Thank you. It helped me to solve the issue.
