### ISSUE TITLE
WsFederationServiceFactory IUserService registration

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer3.WsFederation#64]
The `IUserService` registration for `WsFederationServiceFactory` is currently set by the registration in `IdentityServerServiceFactory`, however it has a public setter. 

Is this intended? I've attempted to set a different user service here but I'm met with various InvalidOperationException errors as the two user services clash.

**Comment by leastprivilege** [comment]
You really have to use the same user service.

I think we only tried to add some syntactic sugar when we added the ctor param.

**Comment by scottbrady91** [comment]
Yeah, I thought it was a bit odd to see the public property `UserService` in the factory, despite it always being assigned in the constructor.

Worth a PR removing the setter?

**Comment by leastprivilege** [comment]
that's a breaking change..

**Comment by scottbrady91** [comment]
Boo. No worries then.
