### ISSUE TITLE
Minor tweak in SignInResponseGenerator for testing purposes

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/IdentityServer3.WsFederation#69]
For testing purposes, would it be possible to change the access on the `CreateSubjectAsync` method in `SignInResponseGenerator` from private to protected? (https://github.com/IdentityServer/IdentityServer3.WsFederation/blob/master/source/WsFederationPlugin/ResponseHandling/SignInResponseGenerator.cs#L100)

Then, I could easily call this method in a test in order to test the entire claims handling in situ.

**Comment by scottbrady91** [comment]
Could you not test the public `GenerateResponseAsync` instead of changing the source code? It wouldn't require too much effort to extract the claims from the resulting security token. The plugin only uses security tokens from the System.IdentityModel namespace, so you wouldn't be adding much of a dependency to the test.

Also, are you unit/integration testing this plugin?

**Comment by vidarkongsli** [comment]
Well, sure. But I would say it would be quite more difficult. Instead of having an `ClaimsIdentity` to test on right away, one would have to call `.Write(TextWriter)`, parse the XML, and extract the SAML assertions from there.  In addition, the test would require more setup (X509 cert, etc.) in order to facilitate signing the response. Possible, yes. Changing the access modifier would be in my mind a simpler option, so that a subclass used for testing could call it directly.

**Comment by vidarkongsli** [comment]
I am trying to walk down the path of calling `GenerateResponseAsync` as suggested above. It seems is dependent on having an OwinContext wired, and I have a really hard time wiring one up for the test. I notice that some internal tests in IdSrv use the `[AutofacConfig](https://github.com/IdentityServer/IdentityServer3/blob/68fe9f496ecbc7a10c571dc769f0fbefb8ce7fde/source/Core/Configuration/Hosting/AutoFacConfig.cs#L33)` class to do this, but this is `internal` so I cannot get to it...

**Comment by leastprivilege** [comment]
send a PR?
