### ISSUE TITLE
Question: Ignoring ReturnUrl Parameter

### ISSUE THREAD

**Issue by Saftpresse99** [IdentityServer/IdentityServer3.WsFederation#77]
Hi,
if a user clicks a link and he is not authenticated (options.aspx for example) the wsfederation module redirect the user to the sts where the user is authenticated.  So far so good.
I put the reply attribute with a valid value in the web.config at the RP. For example http://www.localhost:82828/login/landing.aspx. If authentification is successful the user is redirected to the landing.aspx from the STS. But before the page is hit the wsfederation module  jumps in and initiate another redirect that i don't want. It's redirecting to options.aspx .
I evaluate that in the wctx Paramter a return url is encoded (ru param). In my example options.aspx. How can i prevent the wsfederation module from redirecting the request to options.aspx? I will always a redirection to landing.aspx.
Thank you!

**Comment by leastprivilege** [comment]
Sorry . this is not about identityserver. Please use SO or some Microsoft forum.

**Comment by Saftpresse99** [comment]
Thank you,
i have  made post at SO: http://stackoverflow.com/questions/39116542/ignoring-returnurl-parameter-in-wif-wsfederation .
