### ISSUE TITLE
Error Page for CustomRequestValidator

### ISSUE THREAD

**Issue by thebodaciousd** [IdentityServer/IdentityServer3.WsFederation#83]
I am using a customer ICustomWsFederationRequestValidator to check if user should be allowed to access the RP based on their claims.  The ValidateSignInRequestAsync runs correctly and I set an error response like this:

```
public class CustomWsFederationRequestValidator : ICustomWsFederationRequestValidator
{
	private OwinContext _ctx;
	private readonly ILogger _logger;

	public CustomWsFederationRequestValidator(OwinEnvironmentService owinEnv)
	{
		_logger = LogManager.GetCurrentClassLogger();
		_ctx = new OwinContext(owinEnv.Environment);
	}

	public Task<SignInValidationResult> ValidateSignInRequestAsync(SignInValidationResult request)
	{
		try
		{
			if (request.Subject.Identity.IsAuthenticated)
			{
				int id = int.Parse(request.Subject.FindFirst(JwtClaimTypes.Subject).Value);

				_logger.Info("RequestValidate:: Id: {0}, RelayingParty: {1}, ReplyUrl: {2}", id, request.RelyingParty.Name, request.ReplyUrl);

				if (true) //this is normally a permission check
				{
					request.IsError = true;
					request.Error = "You do not have permission to access this site.";
					request.ErrorMessage = "You do not have permission to access this site.";
				}
			}
		}
		catch (Exception ex)
		{
			_logger.Error(ex, "Unable to validate request!");
			request.IsError = true;
			request.Error = "Unable to verify request!";
			request.ErrorMessage = "Unable to verify request!";
		}

		return Task.FromResult(request);
	}
}
```

I was hoping this would get spit out to the error page like ICustomRequestValidator does for IdentityServer, but instead I just get a BadRequest error where json appears in the browser.  AM I using this incorrectly or is that just how the response gets set for WsFed?

**Comment by scottbrady91** [comment]
Authorization logic such as this doesn't belong within IdentityServer. IdentityServer is purely authentication (verifying their identity/who they are, not what they are allowed to do).

If they don't have permission to access that relying party then they can still authenticate. When they are returned to your application (the relying party), it is your application's responsibility to check the authenticated users claims and that's when an unauthorized error should be generated.

**Comment by thebodaciousd** [comment]
I understand the premise, just disappointed that the core and this plugin treat the request validators differently.  Thanks
