### ISSUE TITLE
Windows Server 2008 r2 /wsfed url being served as a static file by IIS

### ISSUE THREAD

**Issue by Torinth** [IdentityServer/IdentityServer3.WsFederation#84]
Hi, I apologize for the lack of detailed information I have for a problem we are seeing.  We have installed a product using idsvr3 on a Windows Server 2008 R2 instance.  When the business product redirects to the idp using the /wsfed route we are getting an error that the file doesn't exist and that the module was the static file module.  I feel like we are missing something installed on the machine to enable features that might come by default with server 2012 and up.  We have installed it on several other 2008 r2 machines that work fine but they are more QA machines so might have had some dev tools installed on them to enable all the dependencies.

Is there a list of installed dependencies somewhere or does this stick out in any way?  I wont have access to the server again until Monday to try and pull logs.  Any thoughts would be greatly appreciated.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
