### ISSUE TITLE
Silent sign-in

### ISSUE THREAD

**Issue by craigbroadman** [IdentityServer/IdentityServer3.WsFederation#86]
Hi

I have come across a number of articles that discuss a similar matter but I cannot find a definitive answer.

My company would like to begin using Identity Server 3, however one of the requirements is to be able to authenticate an external user without them having to manually enter their credentials.

Essentially, the external user has their own CRM.

-The CRM holds their username and password for our software. 
-They then click a button in their CRM to launch our application
-This redirects them to our website with a payload containing their credentials
-We call a web service to authenticate the user

It is fundamental that we do not change this process for our partners.

Can I implement a custom service provider to provide the authentication or is there some other way of achieving this? If so, could you point me in the right direction for how this can be done? 

Many thanks
Craig

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by craigbroadman** [comment]
Thanks for your response, I have added a question to stackoverflow 
http://stackoverflow.com/questions/41480469/identity-server-3-silent-sign-in-sign-in-without-login-page-including-singl
