### ISSUE TITLE
FedAuth Cookie is empty

### ISSUE THREAD

**Issue by codestellar** [IdentityServer/IdentityServer3.WsFederation#87]
I am integrating IdentityServer 3 Ws-Fed with SharePoint to authenticate users.
When the user logs in, the sign in response contains the claims but HTTPContext.Current in Sharepoint Custom Module contains 3 errors each one of them is saying "Value Cannot be null" and interestingly parameter name is also null. 
Looks like there is an issue in Identity Server 3 while sending the response object.
Also, SAML token is there but FedAuth Cookie is empty:

```
﻿<?xml version="1.0" encoding="utf-8"?><SP>

</SP>
```

**Comment by scottbrady91** [comment]
Answered on https://github.com/IdentityServer/IdentityServer3/issues/3694

**Comment by brockallen** [comment]
Dup;closing.
